require 'albacore'

version = "1.3.1"
common_dir = "Common"
build_configuration = "Release"

assemblyinfo :assemblyinfo do |asm|
	Dir.mkdir(common_dir) unless File.directory?(common_dir)
	asm.version = version
	asm.file_version = version
	asm.product_name = "Agatha"
	asm.copyright = "Copyright (C) Davy Brion"
	asm.output_file = "#{common_dir}/CommonAssemblyInfo.cs"
	asm.custom_data = ['// This code was generated by the Rakefile', '// Don\'t change it directly, instead edit Rakefile.rb']
end

msbuild :build => :assemblyinfo do |msb|
	msb.solution = "Agatha.sln"
	msb.targets :clean, :build
	msb.properties :configuration => build_configuration
end

xunit :test => :build do |xunit|
	xunit.command = "libs/xunit.net/xunit.console.clr4.exe"
	xunit.assembly = "build/#{build_configuration}/Tests.dll"
	running_local = ENV['BUILD_NUMBER'].nil?
	xunit.parameters "/html test_results.html" if running_local
end

task :default => [:test]
