using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyProduct("Agatha")]
[assembly: AssemblyCopyright("Copyright (C) Davy Brion")]
[assembly: AssemblyVersion("1.3.1")]
[assembly: AssemblyFileVersion("1.3.1")]

// This code was generated by the Rakefile
// Don't change it directly, instead edit Rakefile.rb
